/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK */

#ifndef _Included_org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK
#define _Included_org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK
 * Method:    convertirGrises
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK_convertirGrises
  (JNIEnv *, jobject, jobject, jobject);

JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK_convertirSepia
        (JNIEnv *, jobject, jobject, jobject);
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK_ponerMarco1
        (JNIEnv *, jobject, jobject, jobject);
JNIEXPORT void JNICALL Java_org_jordi_pruebafacebook2017sdk1_ImgProcesadoNDK_ponerMarco2
        (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
